channels:
- conda-forge
dependencies:
- python=3.10.11
- pip<=23.1.2
- pip:
  - mlflow==2.3
  - cffi==1.15.1
  - cloudpickle==2.2.1
  - cupy-cuda11x==11.0.0
  - defusedxml==0.7.1
  - distributed==2022.12.1
  - graphviz==0.20.1
  - lightgbm==3.3.5
  - matplotlib==3.7.1
  - pandas==1.5.3
  - pathlib==1.0.1
  - pyarrow==9.0.0
  - pytest==7.2.2
  - scikit-learn==1.2.2
  - typing-extensions==4.5.0
name: mlflow-env
